# ===========================
# ros2_controllers.yaml
# ===========================
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    braccio_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

braccio_arm_trajectory_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity